# Generated by Django 5.0.3 on 2024-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_of_pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
